### PR TITLE
[monarchy][factory] removing unexpected added bots from group

### PR DESCRIPTION
**Pull request by Khumoyun098**

### CODE REVIEW

**Comment by JasurbekNURBOYEV** [comment]
Keep in mind to leave space after # when using comments
#comment -> # comment

**Comment by Khumoyun098** [comment]
Added single message delete command

**Comment by JasurbekNURBOYEV** [comment]
good job

**Comment by UlugbekXatamjonov** [comment]
Hi. How are you

**Comment by Nurikjohn** [comment]
@JasurbekNURBOYEV ozizga oziz comment yozvos di. oylamman

**Pull request merged**
